name: CI/CD

on:
  push:
    branches:
      - feat/* 
      - feature/*
      - main
env:
  PYTHON_VERSION: 3.8

jobs:
  test:
    name: Perform vulnerability scans
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Checkout Terraform Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: |
          echo "this is a mock terraform init step"
          # terraform init

      - name: Terraform validate
        run: |
          terraform validate

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform

  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout Terraform Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          echo "this is a mock terraform init step"
          # terraform init

      - name: Terraform Plan
        run: |
          echo "this is a mock terraform plan step"
          echo "docker_image_uri - ${{ needs.build.outputs.docker_image_uri }}"          
          # terraform plan -var "s3_data_provider_docker_image_uri=${{ needs.build.outputs.docker_image_uri }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          echo "this is a mock terraform apply step"
          echo "docker_image_uri - ${{ needs.build.outputs.docker_image_uri }}"          
          # terraform apply -auto-approve -var "s3_data_provider_docker_image_uri=${{ needs.build.outputs.docker_image_uri }}"